### ISSUE TITLE
Support browsers that don't have 'import' keyword (using a shim?)

### ISSUE THREAD

**Issue by dragontamer8740** [memoryholecc/frontend#1]
Old versions of Firefox, and current versions of Seamonkey/Pale Moon, do not have `javascript.options.dynamicImport` or the `import` javascript keyword yet. Therefore, the main page is a blank white window when viewed in those browsers.

    SyntaxError: expected expression, got keyword 'import'

Would it be possible to have a separate code path for browsers that can't use `import`?

See also: https://github.com/rich-harris/shimport

Would using that or some similar wrapper be considered acceptable?

**Comment by memoryholedevs** [comment]
Hello, we have added support for legacy browsers through https://github.com/vitejs/vite/tree/main/packages/plugin-legacy
